// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickstartIdentityServer.DBManager;

namespace QuickstartIdentityServer.Data.Migrations.Permission.ConfigurationDb
{
    [DbContext(typeof(PermissionConext))]
    [Migration("20190222020934_addappcode")]
    partial class addappcode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.AppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(8);

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Order");

                    b.Property<long>("Ts");

                    b.Property<int>("UpdateId");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("App");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppCode")
                        .HasMaxLength(8);

                    b.Property<string>("Code")
                        .HasMaxLength(8);

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int>("Order");

                    b.Property<long>("Ts");

                    b.Property<int>("UpdateId");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("AppCode");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionName")
                        .HasMaxLength(20);

                    b.Property<string>("ControllerName")
                        .HasMaxLength(20);

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ModuleId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int>("Order");

                    b.Property<long>("Ts");

                    b.Property<int>("UpdateId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Url")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.RoleAppAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(8);

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleAppAdmin");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<long>("Ts");

                    b.Property<int>("UpdateId");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.RoleModuleMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppCode")
                        .HasMaxLength(8);

                    b.Property<int>("ModuleId");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("AppCode");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleModuleMap");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.RolePermissionMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("PermissionId");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionMap");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .HasMaxLength(20);

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystemAdmin");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Pwd")
                        .HasMaxLength(32);

                    b.Property<long>("Ts");

                    b.Property<int>("UpdateId");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.UserRoleMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleMap");
                });

            modelBuilder.Entity("QuickstartIdentityServer.DBManager.UserRoleMap", b =>
                {
                    b.HasOne("QuickstartIdentityServer.DBManager.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuickstartIdentityServer.DBManager.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
